trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      cd lens
      npm install
      tsc
      npm test
    displayName: 'lens'
    condition: succeededOrFailed()

  - script: |
      cd codeondemand
      npm install
      tsc
      npm test
    displayName: 'codeondemand'
    condition: succeededOrFailed()

  - script: |
      cd nav
      npm install
      tsc
      npm test
    displayName: 'nav'
    condition: succeededOrFailed()

  - script: |
      set -e
      cd examples/lens/dragon
      npm install
      tsc
      npm test
    displayName: 'lens/dragon'
    condition: succeededOrFailed()

  - script: |
      set -e
      cd examples/lens/tictactoe
      npm install
      tsc
    displayName: 'lens/tictactoe'
    condition: succeededOrFailed()

  - script: |
      set -e
      cd examples/codeondemand/tictactoe
      npm install
      tsc
    displayName: 'codeondemand/cpq'
    condition: succeededOrFailed()

  - script: |
      set -e
      cd examples/codeondemand/cpq
      npm install
      tsc
    displayName: 'codeondemand/cpq'
    condition: succeededOrFailed()

